// @generated by expo-yarn-workspaces

import 'expo/build/Expo.fx';
import { activateKeepAwakeAsync } from 'expo-keep-awake';


if (__DEV__) {
  activateKeepAwakeAsync();
}

import "expo-router/entry";
